### ISSUE TITLE
The URL mentioned in "basics/rule2.html" is invalid

### ISSUE THREAD

**Issue by onelife** [aroberge/reeborg-docs#10]
> Picture adapted from the public archive of the `U.S. Naval Historical Center
<http://www.history.navy.mil/photos/pers-us/uspers-h/g-hoppr.htm>`__

Now, it has been changed to https://www.history.navy.mil/content/history/nhhc/our-collections/photography/numerical-list-of-images/nhhc-series/nh-series/NH-96000/NH-96566-KN.html.

**Comment by aroberge** [comment]
Thanks - I will need to fix this, after which I will close this issue.

**Comment by onelife** [comment]
Hi aroberge, 
Reeborg's world is super cool! I want to teach my kids programming by using this tutorial. Thanks a lot for your hard work!
I am currently trying to get familiar by translating it to Chinese and will raise pull request when done.

**Comment by aroberge** [comment]
Thank you very much!

Doing a full translation can be a **lot** of work.

You can, of course, translate the tutorial and I will be happy to add your language: there are, after all, more Chinese speakers in this world than any other language. (I wish I could read Chinese...)

If you are ambitious, you can also, translate the user interface and some terms uses (see https://github.com/aroberge/reeborg/tree/master/src/lang for some languages), or even translate the basic instructions (`move`, `take`, etc.) by translating/adapting the content of reeborg_en.py (https://github.com/aroberge/reeborg/blob/master/src/python/reeborg_en.py) or the javascript version (https://github.com/aroberge/reeborg/tree/master/src/js/programming_api)

Whatever you do to contribute, I thank you.

**Comment by onelife** [comment]
I will do although it may take time. Interface will be the next item in my TODO list.
