### ISSUE TITLE
Question - about RUR onload()

### ISSUE THREAD

**Issue by abixadamj** [aroberge/reeborg-docs#13]
Dear @aroberge - please answer - is somewheere docs about possible RUR command for onload()? I want to make Blockly (Py) as default view when world is loading... Also I think I wiill want some more changes in the future, and that is why I am asking about docs...

Best,
Adam

**Comment by aroberge** [comment]
Hello @abixadamj,

There is no documentation about the code itself. 

I believe that if you change https://github.com/aroberge/reeborg/blob/master/src/js/rur.js#L151
```
RUR.initial_defaults.input_method = 'python'
```
 from "python" to "blockly-py", it will have the desired effect.

**Comment by abixadamj** [comment]
I did:
```
  "onload": [
    "RUR.state.visible_grid = true;",
    "RUR.initial_defaults.input_method = 'blockly-py';"
  ],
```
but it does not effect... ;-(

**Comment by abixadamj** [comment]
I have tried:
```
  "onload": [
    "RUR.state.visible_grid = true;",
    "RUR.state.input_method = 'blockly-py';",
    "RUR.state.onload_programming_language = 'blockly-py';",
    "RUR.initial_defaults.input_method = 'blockly-py';"
  ],
```
also without any luck...

**Comment by aroberge** [comment]
I'm sorry, I misunderstood. I thought you wanted to create a customized version of Reeborg's World.

Trying to use "onload" will almost certainly not work - as you found out.  The way that the starting mode is determined is as follows:

1. First, the URL is parsed. If it contains information about the starting mode, it is used.
2. If not, the local storage is looked at: this allows to resume from previously saved work.
3. Finally, the default values in the code are used.

My suggestion would be to provide a custom link, such as https://reeborg.ca/reeborg.html?lang=en&mode=blockly-py&menu=worlds%2Fmenus%2Freeborg_intro_en.json&name=Alone&url=worlds%2Ftutorial_en%2Falone.json

**Comment by abixadamj** [comment]
Dear @aroberge - sorry for that delay. Thank you for explanation. Custom link is nice ;-)
